#!/bin/bash

function usage {
  echo "wib_program_remote_apa <apa number>"
}

if [ -z "$1" ] ; then
  usage
  exit 1
fi 

if [ $1 = 1 ] || [ $1 = 2 ] || [ $1 = 3 ] || [ $1 = 4 ] || [ $1 = 5 ] || [ $1 = 6 ] || [ $1 = 9 ]; then
    declare -a arr=("np04-wib-${1}01" "np04-wib-${1}02" "np04-wib-${1}03" "np04-wib-${1}04" "np04-wib-${1}05")
else
  usage
  echo "apa is 1-6"
  exit 1
fi

cd /nfs/sw/wib/WIBSoftwareTrunk/
source env.sh

tmpscriptcheck=`mktemp -t wib_program_remote_check.XXXXXXX.script`
cat << EOF > $tmpscriptcheck
read FLASH.RECONFIG_BUSY
quit
EOF

tmpscriptreset=`mktemp -t wib_program_remote_reset.XXXXXXX.script`
cat << EOF > $tmpscriptreset
write FLASH.RECONFIG 1
quit
EOF

## now loop through the above array
for i in "${arr[@]}"
do
    echo "Restarting ${i}..."
     
    tmplog=`mktemp -t wib_program_remote_check.XXXXXXX.log`
    BUTool.exe -w $i -X $tmpscriptcheck >& $tmplog
    isgood=$(sed -nr '/FLASH.RECONFIG_BUSY: 0x00000000/p' $tmplog)
    rm $tmplog
    if [ -z "$isgood" ]; then
       echo "Error: Flash reconfig is already busy, is another flash programming in progress for this WIB?"
       echo "       Finish that up and then we can reset"
    else
      BUTool.exe -w $i -X $tmpscriptreset
    fi
done
rm $tmpscriptcheck
rm $tmpscriptreset
