#!/bin/bash

function usage {
  echo "wib_program_remote <wib url> <firmware file>" >&2
}

if [ -z "$1" ] ; then
  usage
  exit 1
fi 

if [ -z "$2" ] ; then
  usage
  exit 1
fi 

cd /nfs/sw/wib/WIBSoftwareTrunk/
source env.sh

tmpscript=`mktemp -t wib_program_remote_check.XXXXXX.script`
cat << EOF > $tmpscript
flash_wr yesdoitnow ${2}
quit
EOF

nohup BUTool.exe -w $1 -X $tmpscript
