echo Configuring WIB: VST RCE with fake data -- counter
add_device WIB 192.168.200.2

write SYSTEM.SLOW_CONTROL_DND 1

# pdts timing, tgrp 1, 0 for backplane timing, 1 for front panel
checkedResetWIBAndCfgDTS 0 0 0 # second arg is timing partition

# set to 1 for each FEMB you want to be fake
configWIBFakeData 0 1 1 1

fpwr 1 1
sleep 1
configFEMBFakeData 1 2

startStreamToDAQ

status 4 DTS

write SYSTEM.SLOW_CONTROL_DND 0
