#!/bin/bash

function usage {
  echo "wib_program_remote_apa <apa number> <firmware file>"
}

if [ -z "$1" ] ; then
  usage
  exit 1
fi 

if [ -z "$2" ] ; then
  usage
  exit 1
fi 

if [ $1 = 1 ] || [ $1 = 2 ] || [ $1 = 3 ] || [ $1 = 4 ] || [ $1 = 5 ] || [ $1 = 6 ] || [ $1 = 9 ]; then
    declare -a arr=("np04-wib-${1}01" "np04-wib-${1}02" "np04-wib-${1}03" "np04-wib-${1}04" "np04-wib-${1}05")
else
  usage
  echo "apa is 1-6"
  exit 1
fi

cd /nfs/sw/wib/WIBSoftwareTrunk/
source env.sh

tmpscript=`mktemp -t wib_program_remote.XXXXXXX.script`
cat << EOF > $tmpscript
flash_wr yesdoitnow ${2}
quit
EOF

## now loop through the above array
for i in "${arr[@]}"
do
    datetime=`date -Iseconds`
    logfilename=`pwd`/scripts/program_logs/wib_program_${i}_${datetime}.log
    echo "Starting $i logfile $logfilename"

    nohup BUTool.exe -w $i -X $tmpscript >& $logfilename &
done
